giftBox: 
  chestSetting: 
    IRON_BLOCK: 
      chestKey: TEST2
      dropGroup: 
      - drops:
        - itemKey: TEST
          percent: 100
        probability: 1
  chestDataSetting:
    TEST2:
      item:
        ==: org.bukkit.inventory.ItemStack
        type: IRON_BLOCK
        damage: 0
        amount: 1
  dataSetting: 
    TEST: 
      dropGroup: 
      - drops: 
        - item: 
            ==: org.bukkit.inventory.ItemStack
            type: WOOD_AXE
            damage: 0
            amount: 1
          percent: 100
        probability: 1
  commandSetting: 
    usage: /<GiftBox|gb> <子命令>
    description: 使用此命令来操作礼物盒子插件
    get:
      usage: /<GiftBox|gb> <get|g> <chestKey>
      description: 使用此命令来直接获取礼物盒子信息
      permission: GiftBox.admin
      permission-message: 你没有权限使用礼物盒子插件帮助命令
    help: 
      usage: /<GiftBox|gb> <help> [GifBox命令]
      description: 使用此命令来显示礼物盒子插件帮助信息
      permission: GiftBox.help
      permission-message: 你没有权限使用礼物盒子插件帮助命令
    reload: 
      usage: /<GiftBox|gb> <reload>
      description: 使用此命令来重新加载配置文件
      permission: GiftBox.admin
      permission-message: 你没有权限重新加载配置文件