name: GifBox
version: 0.0.1
authors: [Cthuwork]

main: net.cthuwork.gifbox.GifBox

commands:
  GifBox:
    aliases: gf
permissions:
  GifBox.help:
    description: 允许使用自定义掉落插件帮助命令
    default: true
  GifBox.reload:
    description: 允许重新加载配置文件
    default: op