name: GiftBox
version: 1.0.0
authors: [Cthuwork]

main: net.cthuwork.giftbox.GiftBox

commands:
  GiftBox:
    aliases: GB
permissions:
  GiftBox.help:
    description: 允许使用GiftBox插件帮助命令
    default: true
  GiftBox.reload:
    description: 允许重新加载配置文件
    default: op
