name: GiftBox
version: 1.0.0
authors: [Cthuwork]

main: net.cthuwork.giftbox.GiftBox

commands:
  GiftBox:
    aliases: gb
permissions:
  GiftBox.admin:
    description: 允许使用GiftBox管理员命令
    default: op
  GiftBox.help:
    description: 允许使用GiftBox插件帮助命令
    default: true